project:
  type: website

website:
  favicon: favicon.png
  title: "Codenym"
  navbar:
    right:
      - index.qmd
      - analysis.qmd
      - icon: github
        href: https://github.com/codenym
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

