project:
  type: website

website:
  favicon: favicon.png
  title: "Codenym"
  margin-header: subscribe.html
  site-url: https://codenym.github.io/website/
  description: "The Codenym blog sharing open source datasets and insights on social justice and government transparency topics"
  navbar:
    right:
      - index.qmd
      - analysis.qmd
      - icon: github
        href: https://github.com/codenym
      - icon: rss
        href: rss.xml
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

