project:
  type: website

website:
  title: "."
  navbar:
    right:
      - index.qmd
      - articles.qmd
      - icon: github
        href: https://github.com/codenym
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

